server:
  port: 8086
spring:
  application:
    name: aml-screening-job
  datasource:
    url: jdbc:postgresql://localhost:5432/csti
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
csti:
  app:
    jwtSecret: cstiTestSecretKey
    jwtExpirationMs: 86400000
